// Central icon registry so the whole app uses one consistent set (Feather / Fi).
export {
  FiHome,
  FiUser,
  FiUsers,
  FiCalendar,
  FiClock,
  FiDollarSign,
  FiLogOut,
  FiLogIn,
  FiCheckCircle,
  FiCheck,
  FiX,
  FiXCircle,
  FiEdit2,
  FiEdit3,
  FiSearch,
  FiInbox,
  FiBriefcase,
  FiCamera,
  FiUserCheck,
  FiUmbrella,
  FiTrendingUp,
  FiMail,
  FiPhone,
  FiMapPin,
  FiChevronLeft,
  FiChevronRight,
  FiPlusCircle,
  FiArrowRight,
  FiFileText,
  FiGrid,
  FiActivity,
  FiDownload,
} from 'react-icons/fi';
